export const availableSkillList: string[] = [
  // Programming languages
  'JavaScript',
  'TypeScript',
  'Python',
  'Java',
  'C++',
  'C#',
  'Ruby',
  'Go',
  'Swift',
  'PHP',
  'Rust',
  'Kotlin',
  'Dart',
  'Objective-C',
  'Scala',
  'R',
  'Perl',
  'Haskell',
  'Elixir',
  'F#',
  'Lua',
  'VB.NET',
  'MATLAB',
  'COBOL',
  'Fortran',

  // Web development frameworks
  'Vue.js',
  'React',
  'Angular',
  'Svelte',
  'Next.js',
  'Nuxt.js',
  'Gatsby',
  'Express.js',
  'NestJS',
  'Meteor',
  'Ruby on Rails',
  'Django',
  'Flask',
  'Spring Boot',
  'Laravel',
  'Symfony',
  'ASP.NET',
  'CakePHP',
  'Ember.js',
  'Backbone.js',

  // Mobile development
  'React Native',
  'Flutter',
  'Ionic',
  'SwiftUI',
  'Android Studio',
  'Xcode',
  'Kotlin Multiplatform',
  'Cordova',
  'NativeScript',
  'Xamarin',
  'Jetpack Compose',

  // Data science & machine learning
  'TensorFlow',
  'PyTorch',
  'Pandas',
  'NumPy',
  'Scikit-learn',
  'Keras',
  'Matplotlib',
  'Data Visualization',
  'Data Analysis',
  'Deep Learning',
  'NLTK',
  'OpenCV',
  'Gensim',
  'Hugging Face',

  // DevOps & Cloud
  'AWS',
  'Azure',
  'Google Cloud',
  'Docker',
  'Kubernetes',
  'Terraform',
  'CI/CD',
  'Linux',
  'Shell Scripting',
  'Ansible',
  'Jenkins',
  'Travis CI',
  'CircleCI',
  'GitLab CI',
  'Vagrant',
  'OpenShift',
  'CloudFormation',

  // Databases
  'SQL',
  'NoSQL',
  'MySQL',
  'PostgreSQL',
  'MongoDB',
  'Redis',
  'Oracle Database',
  'Cassandra',
  'GraphQL',
  'SQLite',
  'Elasticsearch',
  'Couchbase',
  'Firebase Realtime Database',
  'DynamoDB',
  'MariaDB',
  'Memcached',

  // Soft skills
  'Communication',
  'Teamwork',
  'Problem Solving',
  'Leadership',
  'Time Management',
  'Critical Thinking',
  'Adaptability',
  'Creativity',
  'Negotiation',
  'Conflict Resolution',

  // Miscellaneous technical skills
  'Project Management',
  'Agile',
  'Scrum',
  'SEO',
  'Digital Marketing',
  'UX/UI Design',
  'Graphic Design',
  'Public Speaking',
  'Customer Service',
  'Financial Analysis',

  // Sales & Marketing
  'Sales Strategy',
  'Lead Generation',
  'Account Management',
  'Market Research',
  'Content Marketing',
  'Brand Management',
  'Email Marketing',
  'Social Media Marketing',
  'Influencer Marketing',
  'Copywriting',

  // Customer Service & Support
  'Customer Relationship Management (CRM)',
  'Call Center Operations',
  'Complaint Resolution',
  'Empathy',
  'Active Listening',
  'Product Knowledge',
  'Multitasking',
  'Patience',
  'Client Retention',
  'Service Recovery',

  // Finance & Accounting
  'Financial Planning',
  'Budgeting',
  'Taxation',
  'Auditing',
  'Accounts Payable',
  'Accounts Receivable',
  'Cost Accounting',
  'Financial Reporting',
  'Risk Management',
  'Investment Analysis',

  // Human Resources
  'Talent Acquisition',
  'Recruitment',
  'Onboarding',
  'Employee Relations',
  'HR Compliance',
  'Compensation and Benefits',
  'Training and Development',
  'Performance Management',
  'Conflict Resolution',
  'Employee Engagement',

  // Healthcare & Nursing
  'Patient Care',
  'Medical Terminology',
  'Medication Administration',
  'Clinical Documentation',
  'IV Therapy',
  'Wound Care',
  'Critical Thinking in Healthcare',
  'Infection Control',
  'Patient Education',
  'Phlebotomy',

  // Education & Training
  'Curriculum Development',
  'Lesson Planning',
  'Classroom Management',
  'Student Assessment',
  'Special Education',
  'Adult Learning Principles',
  'eLearning',
  'Instructional Design',
  'Training Facilitation',
  'Educational Technology',

  // Administration & Office Support
  'Office Management',
  'Calendar Management',
  'Data Entry',
  'Filing',
  'Travel Coordination',
  'Document Preparation',
  'Office Equipment Management',
  'Meeting Coordination',
  'Event Planning',
  'Mail Management',

  // Legal & Compliance
  'Contract Drafting',
  'Legal Research',
  'Compliance Auditing',
  'Regulatory Affairs',
  'Risk Assessment',
  'Litigation Support',
  'Corporate Governance',
  'Employment Law',
  'Due Diligence',
  'Mediation',

  // Logistics & Supply Chain
  'Supply Chain Management',
  'Inventory Management',
  'Logistics Coordination',
  'Procurement',
  'Vendor Management',
  'Warehouse Operations',
  'Demand Forecasting',
  'Shipping and Receiving',
  'Transportation Management',
  'Logistics Optimization',

  // Construction & Trades
  'Project Scheduling',
  'Blueprint Reading',
  'Carpentry',
  'Plumbing',
  'Electrical Wiring',
  'HVAC',
  'Masonry',
  'Welding',
  'Concrete Work',
  'Safety Compliance',

  // Arts & Creative
  'Photography',
  'Videography',
  'Video Editing',
  'Illustration',
  'Drawing',
  'Painting',
  'Sculpture',
  'Music Composition',
  'Sound Design',
  'Fashion Design',

  // Retail & Hospitality
  'Cash Handling',
  'POS Systems',
  'Inventory Control',
  'Merchandising',
  'Customer Service',
  'Event Management',
  'Food Preparation',
  'Housekeeping',
  'Sales Techniques',
  'Upselling',

  // Research & Development
  'Scientific Research',
  'Lab Safety',
  'Data Collection',
  'Experimental Design',
  'Hypothesis Testing',
  'Technical Writing',
  'Report Writing',
  'Patent Research',
  'Product Development',
  'Innovation Management',
];

export const schoolDegrees = [
  {
    label: 'Undergraduate',
    options: [
      { value: 'associate_of_arts', text: 'Associate of Arts (AA)' },
      { value: 'associate_of_science', text: 'Associate of Science (AS)' },
      {
        value: 'associate_of_applied_science',
        text: 'Associate of Applied Science (AAS)',
      },
      { value: 'bachelor_of_arts', text: 'Bachelor of Arts (BA)' },
      { value: 'bachelor_of_science', text: 'Bachelor of Science (BS)' },
      { value: 'bachelor_of_fine_arts', text: 'Bachelor of Fine Arts (BFA)' },
      {
        value: 'bachelor_of_engineering',
        text: 'Bachelor of Engineering (BEng)',
      },
      {
        value: 'bachelor_of_business_administration',
        text: 'Bachelor of Business Administration (BBA)',
      },
      {
        value: 'bachelor_of_technology',
        text: 'Bachelor of Technology (BTech)',
      },
    ],
  },

  {
    label: 'Graduate',
    options: [
      { value: 'master_of_arts', text: 'Master of Arts (MA)' },
      { value: 'master_of_science', text: 'Master of Science (MS)' },
      { value: 'master_of_fine_arts', text: 'Master of Fine Arts (MFA)' },
      {
        value: 'master_of_business_administration',
        text: 'Master of Business Administration (MBA)',
      },
      { value: 'master_of_engineering', text: 'Master of Engineering (MEng)' },
      { value: 'master_of_education', text: 'Master of Education (MEd)' },
      { value: 'master_of_laws', text: 'Master of Laws (LLM)' },
      {
        value: 'master_of_public_health',
        text: 'Master of Public Health (MPH)',
      },
    ],
  },

  {
    label: 'Doctoral',
    options: [
      { value: 'doctor_of_philosophy', text: 'Doctor of Philosophy (PhD)' },
      { value: 'doctor_of_medicine', text: 'Doctor of Medicine (MD)' },
      {
        value: 'doctor_of_dental_surgery',
        text: 'Doctor of Dental Surgery (DDS)',
      },
      { value: 'doctor_of_education', text: 'Doctor of Education (EdD)' },
      { value: 'doctor_of_psychology', text: 'Doctor of Psychology (PsyD)' },
      { value: 'juris_doctor', text: 'Juris Doctor (JD)' },
      {
        value: 'doctor_of_business_administration',
        text: 'Doctor of Business Administration (DBA)',
      },
    ],
  },

  {
    label: 'Other',
    options: [
      { value: 'professional_certificate', text: 'Professional Certificate' },
      { value: 'diploma', text: 'Diploma' },
    ],
  },
];
